### GET
GET http://localhost:3003/api/blogs

### POST
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Rantakeli",
  "author": "Kalle Rantanen",
  "url": "yle.fi",
  "likes": 12
}

### PUT
PUT http://localhost:3003/api/blogs/642242cc03ec8957bdfe5b08
Content-Type: application/json

{
  "likes": "13"
}